//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNQuanLySV
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEMSV_THEOLOP
    {
        public string MaLopM { get; set; }
        public string MaSV { get; set; }
        public string MaMon { get; set; }
        public Nullable<double> DiemDiemDanh { get; set; }
        public Nullable<double> DiemKiemTraGiuaKi { get; set; }
        public Nullable<double> DiemThucHanh { get; set; }
        public Nullable<double> DiemQuaTrinh { get; set; }
        public Nullable<double> DiemThi { get; set; }
        public Nullable<double> DiemTongKet { get; set; }
    
        public virtual LOPMON LOPMON { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
