//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNQuanLySV
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOPMON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOPMON()
        {
            this.DIEMSV_THEOLOP = new HashSet<DIEMSV_THEOLOP>();
        }
    
        public string MaLopM { get; set; }
        public string MaGVHD { get; set; }
        public string MaMon { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIEMSV_THEOLOP> DIEMSV_THEOLOP { get; set; }
        public virtual GIANGVIEN GIANGVIEN { get; set; }
        public virtual MON MON { get; set; }
    }
}
