//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNQuanLySV
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOPQL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOPQL()
        {
            this.SINHVIENs = new HashSet<SINHVIEN>();
        }
    
        public string MaKhoa { get; set; }
        public string MaLop { get; set; }
        public string TenLop { get; set; }
        public string MaGVCN { get; set; }
    
        public virtual GIANGVIEN GIANGVIEN { get; set; }
        public virtual KHOA KHOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SINHVIEN> SINHVIENs { get; set; }
    }
}
