//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNQuanLySV
{
    using System;
    using System.Collections.Generic;
    
    public partial class MON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MON()
        {
            this.LOPMONs = new HashSet<LOPMON>();
        }
    
        public string MaMon { get; set; }
        public string TenMon { get; set; }
        public Nullable<int> SoDVHT { get; set; }
        public string MaKhoa { get; set; }
        public string MaHK { get; set; }
    
        public virtual HOCKI HOCKI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOPMON> LOPMONs { get; set; }
    }
}
